version: '3.8'

services:
  app:
    image: todo-frontend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3000
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:3001